import type {Metadata} from 'next'
import './styles/globals.css'
import React from "react";
import {inter} from '@/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${inter.variable}`}>
            <body>{children}</body>
        </html>
    )
}
